// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCG-_dH5dI7RBDks75rcV0uY2esSNOVDzg',
    appId: '1:934955843190:web:385f8892816608a9bc2957',
    messagingSenderId: '934955843190',
    projectId: 'task-manager-130ee',
    authDomain: 'task-manager-130ee.firebaseapp.com',
    storageBucket: 'task-manager-130ee.firebasestorage.app',
    measurementId: 'G-R1F44302VK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGDWYGqfXb1ZtIgQRveWKZu-gsdlUkvis',
    appId: '1:934955843190:android:a13c1254537c481cbc2957',
    messagingSenderId: '934955843190',
    projectId: 'task-manager-130ee',
    storageBucket: 'task-manager-130ee.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXzOXfatrxcUPcWGXJpr7YdBEcfLeLJc',
    appId: '1:934955843190:ios:3118f8af68f223dcbc2957',
    messagingSenderId: '934955843190',
    projectId: 'task-manager-130ee',
    storageBucket: 'task-manager-130ee.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXzOXfatrxcUPcWGXJpr7YdBEcfLeLJc',
    appId: '1:934955843190:ios:3118f8af68f223dcbc2957',
    messagingSenderId: '934955843190',
    projectId: 'task-manager-130ee',
    storageBucket: 'task-manager-130ee.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCG-_dH5dI7RBDks75rcV0uY2esSNOVDzg',
    appId: '1:934955843190:web:838325a40f41315fbc2957',
    messagingSenderId: '934955843190',
    projectId: 'task-manager-130ee',
    authDomain: 'task-manager-130ee.firebaseapp.com',
    storageBucket: 'task-manager-130ee.firebasestorage.app',
    measurementId: 'G-D4E492Y62P',
  );
}
